# Generated by Django 4.1.4 on 2023-04-20 01:47

import debate_app.validation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("debate_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(max_length=255)),
                ("proposal_id", models.CharField(max_length=255)),
                ("proposal_description", models.TextField(blank=True)),
                ("proposal_args", models.CharField(max_length=255)),
                ("sender_hash", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("governor", models.CharField(max_length=255)),
                ("box", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("start_block", models.IntegerField(default=0)),
                ("end_block", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(unique=True)),
                (
                    "resource_request_status",
                    models.CharField(
                        choices=[
                            ("1", "Accepted"),
                            ("2", "Rejected"),
                            ("3", "Waiting"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceUploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=debate_app.validation.models.upload_loction
                    ),
                ),
                (
                    "resource_request_status",
                    models.CharField(
                        choices=[
                            ("1", "Accepted"),
                            ("2", "Rejected"),
                            ("3", "Waiting"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceInternalDebates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_request_status",
                    models.CharField(
                        choices=[
                            ("1", "Accepted"),
                            ("2", "Rejected"),
                            ("3", "Waiting"),
                        ],
                        default="3",
                        max_length=255,
                    ),
                ),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debate_app.debate",
                    ),
                ),
            ],
        ),
    ]
