# Generated by Django 4.1.4 on 2023-04-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debate_app", "0002_initial"),
        ("validation", "0003_contractproposal_debate"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractproposal",
            name="goal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="debate_app.debategoal",
            ),
            preserve_default=False,
        ),
    ]
