# Generated by Django 4.1.4 on 2023-04-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validation", "0004_contractproposal_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractproposal",
            name="team1_voting_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractproposal",
            name="team2_voting_count",
            field=models.IntegerField(default=0),
        ),
    ]
