# Generated by Django 4.1.4 on 2023-05-02 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validation", "0008_alter_contractproposal_proposal_args_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voteproposal",
            name="reaseon",
        ),
    ]
