# Generated by Django 4.1.4 on 2023-05-03 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debate_app", "0002_initial"),
        ("validation", "0009_remove_voteproposal_reaseon"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateArg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_quote", models.CharField(max_length=255)),
                ("opposing_quote", models.CharField(max_length=255)),
                ("rebuttal_conflict1", models.CharField(max_length=255)),
                ("rebuttal_conflict2", models.CharField(max_length=255)),
                ("rebuttal_conflict3", models.CharField(max_length=255)),
                ("rebuttal_question1", models.CharField(max_length=255)),
                ("rebuttal_question2", models.CharField(max_length=255)),
                ("rebuttal_question3", models.CharField(max_length=255)),
                ("rebuttalConflictDescription1", models.CharField(max_length=255)),
                ("rebuttalConflictDescription2", models.CharField(max_length=255)),
                ("rebuttalConflictDescription3", models.CharField(max_length=255)),
                ("rebuttalQuestionAnswer1", models.CharField(max_length=255)),
                ("rebuttalQuestionAnswer2", models.CharField(max_length=255)),
                ("rebuttalQuestionAnswer3", models.CharField(max_length=255)),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debate_app.debate",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debate_app.debategoal",
                    ),
                ),
            ],
        ),
    ]
