# Generated by Django 4.1.4 on 2023-05-03 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validation", "0010_debatearg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalConflictDescription1",
            new_name="rebuttal_conflict_description1",
        ),
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalConflictDescription2",
            new_name="rebuttal_conflict_description2",
        ),
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalConflictDescription3",
            new_name="rebuttal_conflict_description3",
        ),
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalQuestionAnswer1",
            new_name="rebuttal_question_answer1",
        ),
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalQuestionAnswer2",
            new_name="rebuttal_question_answer2",
        ),
        migrations.RenameField(
            model_name="debatearg",
            old_name="rebuttalQuestionAnswer3",
            new_name="rebuttal_question_answer3",
        ),
    ]
