# Generated by Django 4.1.4 on 2023-05-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "validation",
            "0011_rename_rebuttalconflictdescription1_debatearg_rebuttal_conflict_description1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="debatearg",
            name="opposing_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict_description1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict_description2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_conflict_description3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question_answer1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question_answer2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="rebuttal_question_answer3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatearg",
            name="support_quote",
            field=models.TextField(blank=True),
        ),
    ]
