# Generated by Django 4.1.4 on 2023-05-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debate_app", "0002_initial"),
        ("validation", "0014_daoargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="daoargs",
            name="goal",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="debate_app.debategoal",
            ),
            preserve_default=False,
        ),
    ]
