# Generated by Django 4.1.4 on 2023-04-20 01:47

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "ethereum_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.IntegerField(null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default_profile_pic.png",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DebateMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled", models.BooleanField(default=False)),
                (
                    "invitation_code",
                    models.IntegerField(
                        default=account.models.random_nonce_for_invitation, null=True
                    ),
                ),
                (
                    "member_order",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebateViewers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_vote", models.BooleanField(default=False)),
                ("vote_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Not Active"),
                            ("3", "Finsihed"),
                        ],
                        default="2",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "Support"),
                            ("2", "Opposing"),
                            ("3", "Not Defined"),
                        ],
                        default="3",
                        max_length=255,
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(blank=True, to="account.debatemember"),
                ),
            ],
        ),
    ]
