# Generated by Django 4.1.4 on 2023-04-20 01:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseDebateRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_validation_request_count_on_quote",
                    models.IntegerField(default=1),
                ),
                (
                    "validated_qoals_to_close_count",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "validation_resource1",
                    models.ManyToManyField(
                        blank=True, to="validation.resourceinternaldebates"
                    ),
                ),
                (
                    "validation_resource2",
                    models.ManyToManyField(
                        blank=True, to="validation.resourceexternallink"
                    ),
                ),
                (
                    "validation_resource3",
                    models.ManyToManyField(
                        blank=True, to="validation.resourceuploadfile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebateRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("user_nft_count", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Accepted"),
                            ("2", "Rejected"),
                            ("3", "Waiting"),
                        ],
                        default="3",
                        max_length=255,
                    ),
                ),
                (
                    "close_debate_rules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules.closedebaterules",
                    ),
                ),
            ],
        ),
    ]
