# Generated by Django 4.1.4 on 2023-04-20 01:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Published"),
                            ("2", "Not Published"),
                            ("3", "Rejected"),
                        ],
                        default=2,
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebateGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(200)]
                    ),
                ),
                (
                    "goal_status",
                    models.CharField(
                        choices=[("1", "Not Completed"), ("2", "Completed")],
                        default="0",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebateTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "super_status",
                    models.CharField(
                        choices=[
                            ("0", "waiting"),
                            ("1", "goal1"),
                            ("2", "goal2"),
                            ("3", "goal3"),
                            ("4", "super_vote"),
                        ],
                        default="0",
                        max_length=255,
                    ),
                ),
                (
                    "sub_status",
                    models.CharField(
                        choices=[
                            ("0", "waiting"),
                            ("1", "recess_room1"),
                            ("2", "debate_quote1"),
                            ("3", "debate_quote2"),
                            ("4", "recess_room2"),
                            ("5", "rebuttal_conflict"),
                            ("6", "rebuttal_conflict_description"),
                            ("7", "rebuttal_question"),
                            ("8", "rebuttal_question_answer"),
                            ("9", "sub_vote"),
                        ],
                        default="0",
                        max_length=255,
                    ),
                ),
                ("recess_room1", models.DurationField(default=datetime.timedelta)),
                ("debate_quote1", models.DurationField(default=datetime.timedelta)),
                ("debate_quote2", models.DurationField(default=datetime.timedelta)),
                ("recess_room2", models.DurationField(default=datetime.timedelta)),
                ("rebuttal_conflict", models.DurationField(default=datetime.timedelta)),
                (
                    "rebuttal_conflict_description",
                    models.DurationField(default=datetime.timedelta),
                ),
                ("rebuttal_question", models.DurationField(default=datetime.timedelta)),
                (
                    "rebuttal_question_answer",
                    models.DurationField(default=datetime.timedelta),
                ),
                ("sub_vote", models.DurationField(default=datetime.timedelta)),
                ("goal1", models.DurationField(default=datetime.timedelta)),
                ("goal2", models.DurationField(default=datetime.timedelta)),
                ("goal3", models.DurationField(default=datetime.timedelta)),
                (
                    "super_vote",
                    models.DurationField(default=datetime.timedelta(days=1)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desciption", models.TextField()),
                ("generated_token_request", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "Waiting"),
                            ("2", "Started"),
                            ("3", "Rejected"),
                            ("4", "Accepted"),
                        ],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("slug", models.SlugField(default=uuid.uuid1, unique=True)),
                ("category", models.ManyToManyField(to="debate_app.debatecategory")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goals",
                    models.ManyToManyField(
                        related_name="debate_goals", to="debate_app.debategoal"
                    ),
                ),
            ],
        ),
    ]
