# Generated by Django 4.1.4 on 2023-04-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("debate_app", "0001_initial"),
        ("rules", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debate",
            name="rules",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rules.debaterules"
            ),
        ),
        migrations.AddField(
            model_name="debate",
            name="team_1",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team1",
                to="account.team",
            ),
        ),
        migrations.AddField(
            model_name="debate",
            name="team_2",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team2",
                to="account.team",
            ),
        ),
        migrations.AddField(
            model_name="debate",
            name="timeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="debate_app.debatetimeline",
            ),
        ),
    ]
