# Generated by Django 4.1.4 on 2023-04-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debate_app", "0002_initial"),
        ("account", "0002_initial"),
        ("quote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recessroom",
            name="debate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="debate_app.debate",
            ),
        ),
        migrations.AlterField(
            model_name="recessroom",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.team",
            ),
        ),
    ]
