# Generated by Django 4.1.4 on 2023-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0002_alter_recessroom_debate_alter_recessroom_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debatequote",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "Supporting Quote"),
                    ("2", "Opposing Quote"),
                    ("3", "Rebuttal Conflict Quote"),
                    ("4", "Rebuttal Conflict Description Quote"),
                    ("5", "Rebuttal Question Quote"),
                    ("6", "Rebuttal Question Answer Quote"),
                ],
                max_length=255,
            ),
        ),
    ]
